### ISSUE TITLE
Ore Dictionary

### ISSUE THREAD

**Issue by ZeroInputCtrl** [mallrat208/UBC-Ore-Registrar#11]
I'm using UBCOres 2.8.1 and UBC 0.7. There seems to be an issue when registering all of the ores with the correct ore dictionary entries. It appears that ores are correctly created for each type of stone but 80% of the ores aren't actually registered so when I try to use the Mekanism Miner it doesn't work because the ores that exist around me aren't registered.

http://prntscr.com/8nqofh
http://prntscr.com/8nqofh

**Comment by mallrat208** [comment]
That will be completely on UBC. It takes care of registering vanilla ores and is responsible for registering them with the proper Ore Dictionary tags

**Comment by ZeroInputCtrl** [comment]
I will post this in their issues section as well. I didnt take a screenshot of it but it was also happening for modded ores as well like ae2 and such. Thanks.
