### ISSUE TITLE
GregTech 5 Support

### ISSUE THREAD

**Issue by mura3277** [mallrat208/UBC-Ore-Registrar#15]
Would it be possible to support GregTech5 ore veins?

Specifically BloodAsp's Fork: https://github.com/Blood-Asp/GT5-Unofficial

Thanks for the time.

**Comment by mallrat208** [comment]
I was under the impression that Gregtech natively supported or at least worked with Underground Biomes Constructs. It's Ore dynamically generates it's background texture and then overlays the default 'ore' texture on top of it.

**Comment by mura3277** [comment]
I believe that GT6 does, but GT5 does not unfortunately.

**Comment by mallrat208** [comment]
That's unfortunate then.

The GT Ores are not simple blocks like most mods, they also have tile entities. That's how you can have 'hidden' ore veins and the like. There's no direct easy way to make UBC support it. It would be far easier to have it support UBC.
