### ISSUE TITLE
No Textures using ubc 1.7.2-test45

### ISSUE THREAD

**Issue by Xexanos** [mallrat208/UBC-Ore-Registrar#16]
Just like i wrote in the title:
Zeno410 changed the way ores are done in version 1.7.10-v43 (tile entities to metadata). This seems to be the reason, why all of the texture are now broken.
Here is the corresponding part from the changelog:

> constructs changed from tile entities to multiple metadata'd blocks. For compatibility with old world, the tile entity blocks still exist but there is no way to make more; the recipes create only the new blocks. As yet there is no conversion from the old blocks or items; they continue to exist.

**Comment by O13SC3N3** [comment]
@Zeno410 Be nice if the modded ores were integrated into UBC.the new test works great but I can confirm this with UBC Ore Registrar no ore outside of Vanilla has textures. Rest are Purple Black Checkers. Great for spotting, and a mystery until you run up on it lol.

**Comment by mallrat208** [comment]
@Xexanos @O13SC3N3 

This was fixed with the test46 version of Underground Biomes Constructs
