### ISSUE TITLE
A way to swap rock type with ore name

### ISSUE THREAD

**Issue by labpaw** [mallrat208/UBC-Ore-Registrar#2]
Currently ores translated like: _Basalt Silver Ore_ I want to change it (In Russian localization) to format like: Silver Ore (Basalt). Is it possible to add something like %s tag to ore names? This allow me to swap them.

**Comment by mallrat208** [comment]
Unfortuantely no, UBC itself handles the naming of the block.so any ore
that gets registered gets tagged with the stonetype as a prefix with no way
around it. Even in english it gets a bit wonky depending on what you're
trying to localize. For example Black Granite Air Infused Stone .. is just
wrong.

**Comment by labpaw** [comment]
Oh, ok should be changed in UBC itself. But I think it's almost impossible since it's hard to contact with its author.
