### ISSUE TITLE
Ores light up like redstone while being mined

### ISSUE THREAD

**Issue by ghost** [mallrat208/UBC-Ore-Registrar#20]
UBCOres-1.7.10-0.2.9.4
UndergroundBiomesConstructs-1.7.10-0.8-beta49
I only have thaumcraft ores turned on, don't know about the rest.
![2016-08-12_12 43 14](https://cloud.githubusercontent.com/assets/18379029/17620225/16eba5c0-608b-11e6-8d57-73dc76cd73db.png)

**Comment by mallrat208** [comment]
There's nothing I can do about this unfortunately. My mod uses the UBC api to register ore blocks. UBC itself is what is creating the blocks and determines how they behave.
