### ISSUE TITLE
Ore gen rules borked

### ISSUE THREAD

**Issue by AeroyrHwrdd** [mallrat208/UBC-Ore-Registrar#21]
This seems to be playing havoc with any tweaked ore gen rules. Immersive Engineering copper not obeying.

**Comment by AeroyrHwrdd** [comment]
Seems to be working now. Just a bit temperamental.

**Comment by mallrat208** [comment]
For what it's, this mod doesn't actually take care of the world gen stuff. That's all on Underground Biomes Constructs itself, I just submit the blocks for generation using UBC textures.

**Comment by AeroyrHwrdd** [comment]
Cheers for the explanation.
