### ISSUE TITLE
BoP support doesn't work

### ISSUE THREAD

**Issue by ghost** [mallrat208/UBC-Ore-Registrar#25]
The mod support lists Biomes O' Plenty as supported mod for 1.10.2. I play with this minecraft version, Forge 12.18.3.2221, and BoP 5.0.0.2155, and e.g. Amber Ore doesn't convert when starting a new map. (Thermal Foundation ores are fine.)

![2017-03-08_22 01 15](https://cloud.githubusercontent.com/assets/22047030/23724738/2fb39be6-044e-11e7-8d14-0b6e2906f3b7.png)

**Comment by bookerthegeek** [comment]
It is working in the dev build. Waiting on an update to UBC to push out the update here.

**Comment by mallrat208** [comment]
Closing for now as this has been fixed
