### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bookerthegeek** [mallrat208/UBC-Ore-Registrar#26]
Edit: Silly enter button submitted issue.

Another odd thought for you god sir...

How hard would it be to also do what you do for UBC, to other blocks from other mods? Say Quarried Stone from Railcraft or Limestone from Magneticraft? Just a thought.

**Comment by mallrat208** [comment]
In this instance UBC is doing all the work, I'm just getting all the things in order so that UBC can understand it.

That said I think UBC actually has the ability to add stone types to world gen

**Comment by bookerthegeek** [comment]
Hm... I'll have to look into that then. Thank you. :)
