### ISSUE TITLE
Support for Enviromine

### ISSUE THREAD

**Issue by labpaw** [mallrat208/UBC-Ore-Registrar#3]
Enviromine adds its own coal which can be converted to burning coal if you set fire it. Enviromine open source so it should be easy to support it.
Originally requested here: https://github.com/EnviroMine/EnviroMine-1.7/issues/143

**Comment by mallrat208** [comment]
I'm not sure what it would take to get that working properly. I'll look
into seeing what would take. I think I -might- have to end up making my own
block class specifically for the flammable/burning stuff and pass it
directly to UBC. I'm not sure if that's actually possible however.

**Comment by labpaw** [comment]
If it not possible. At least support for EnviroMine's coal would be great.
