### ISSUE TITLE
[1.12.2] Mod Compat Thread

### ISSUE THREAD

**Issue by bookerthegeek** [mallrat208/UBC-Ore-Registrar#38]
## Heyo!
Hello good sir!

Since UBC has a port now to 1.12, I hereby start the compatibility requests.... :) (I am sure there will be more added to this list, but it is a nice place to centralize everything right?)

### Mods Requested for 1.12.2
- [ ] [Actually Additions](https://minecraft.curseforge.com/projects/actually-additions)
- [ ] [Advanced Rocketry](https://minecraft.curseforge.com/projects/advanced-rocketry)
- [ ] [Applied Energistics 2](https://minecraft.curseforge.com/projects/applied-energistics-2)
- [ ] [Astral Sorcery](https://minecraft.curseforge.com/projects/astral-sorcery)
- [ ] [Biomes O' Plenty](https://minecraft.curseforge.com/projects/biomes-o-plenty)
- [ ] [Crossroads](https://minecraft.curseforge.com/projects/crossroads-mc)
- [ ] [Deep Resonance](https://minecraft.curseforge.com/projects/deep-resonance)
- [ ] [Draconic Evolution](https://minecraft.curseforge.com/projects/draconic-evolution)
- [ ] [Embers](https://minecraft.curseforge.com/projects/embers)
- [ ] [Extreme Reactors](https://minecraft.curseforge.com/projects/extreme-reactors)
- [ ] [Forestry](https://minecraft.curseforge.com/projects/forestry)
- [ ] [Immersive Engineering](https://minecraft.curseforge.com/projects/immersive-engineering)
- [ ] [Industrial Craft](https://minecraft.curseforge.com/projects/industrial-craft)
- [ ] [Magneticraft](https://minecraft.curseforge.com/projects/magneticraft)
- [ ] [Mekanism](https://minecraft.curseforge.com/projects/mekanism)
- [ ] [Mystical Agriculture](https://minecraft.curseforge.com/projects/mystical-agriculture)
- [ ] [NuclearCraft](https://minecraft.curseforge.com/projects/nuclearcraft-mod)
- [ ] Railcraft - Not publicly released, yet.
- [ ] [Project Red](https://minecraft.curseforge.com/projects/project-red-world)
- [ ] [RFTools](https://minecraft.curseforge.com/projects/rftools)
- [ ] [Tech Reborn](https://minecraft.curseforge.com/projects/techreborn)
- [ ] [Thaumcraft](https://minecraft.curseforge.com/projects/thaumcraft)
- [x] [Thermal Foundation](https://minecraft.curseforge.com/projects/thermal-foundation)

### OreGen Overhaul Mods
- [ ] [Base Metals](https://minecraft.curseforge.com/projects/base-metals)
- [ ] [Base Minerals](https://minecraft.curseforge.com/projects/base-minerals)
- [ ] [Geolosys](https://minecraft.curseforge.com/projects/geolosys)
- [ ] [Hardcore ORE](https://minecraft.curseforge.com/projects/hardcore-ore)
- [ ] [Modern Metals](https://minecraft.curseforge.com/projects/modern-metals)
- [ ] [Utility Base Ores](https://minecraft.curseforge.com/projects/utility-base-ores)

**Comment by mallrat208** [comment]
So... apparently Porting from 1.10.2 to 1.12.2 took the following:
Switching from OreRegistry#setupOre to OreRegistry#requestOreSetup
Switching from required loading after UBC to loading before

**Comment by mallrat208** [comment]
Astral Sorcery will probably need to add it's own support given the nature of how it's ore functions. Using UB will effectively kill the ability to find the rock crystals when using the wand

**Comment by mallrat208** [comment]
Ok, so the thing I thought would be a problem is in fact a problem. Changes in how and when blocks can be registered mean that it's going to be near impossible to register mod ores using the requestOreSetup method due to all the various mods loader order dependencies.

**Comment by bookerthegeek** [comment]
Hm... There is an option another mod uses that escapes my tongue at the moment. On first launch it cause a crash after it create a list of all mods that are loaded. I would suggest a screen (Similar to Quarks) that runs on first launch that informs users that they need to reload the pack for the mod to take effect.

Or just cause it to crash with a message in the log (A very noticeable message) that explains that you had to crash to get the ore list.

EDIT:
The mod was [Unified Items](https://minecraft.curseforge.com/projects/unified-items)

**Comment by IronPiston** [comment]
Did loading in UBC ores in 1.10 and before using OreRegistry#requestOreSetup completely replace ores added in, or did it just add them in additionally? 

Sorry if this is a dumb question, but could you not just load in ores based on each included mod, then leave it to the user to disable all other ore generation?

**Comment by mallrat208** [comment]
My mod did nothing extra besides using a built in UBC system. That system doesn't exist anymore and cannot exist due to how blocks and items are registered now. To make this mod work, I'll need to manually create and register the blocks myself now. It's doable but it'll take me time to essentially rewrite the mod

**Comment by mallrat208** [comment]
Alright, so my effort is not required. The person currently maintaining UBC or at least the 1.12.2 port has started rolling in Ore Overlays on their end making this mod pointless. 

I'm going to go ahead and close this. If you have requests you should probably submit them to their repo:
https://github.com/kyeiti/UndergroundBiomesConstructs/issues
