### ISSUE TITLE
Andesite lead drops tin

### ISSUE THREAD

**Issue by labpaw** [mallrat208/UBC-Ore-Registrar#4]
Not sure if it applies to other stone types but andestie lead (id 3243:3, I guess it's IC2 lead) drops tin ore from IC2 when mined.
Forge: 1481
UBC Ore Registrar: 0.2.5.1
UBC: 0.7
IC2: 746

**Comment by mallrat208** [comment]
Looks like I transposed lead and tin in the ic2 section of blocks. I can fix it when I get home from work at around 11 EDT

Thanks for the report :)

**Comment by mallrat208** [comment]
Alright, a new build is being uploaded to Curseforge that should fix this. All existing "Tin" deposits will turn into Lead and all "Lead" will turn into Tin. Should be a non-breaking update

**Comment by labpaw** [comment]
Thanks for the fast fix!
